### PR TITLE
Delete build.bat

### LINKED ISSUE #10: Add support for Windows
### Comment:

Hi all @jakirkham @carterbox - I'd like to support Windows users with conda but I don't know how (the Windows version doesn't require a build). Any help would be most appreciated!

### PR DESCRIPTION
**Pull request by emeryberger**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@conda-forge-admin, please rerender 

Closes https://github.com/conda-forge/scalene-feedstock/issues/10

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
There's a bug in re-rendering. Could try doing this locally

Also have filed issue ( https://github.com/conda-forge/webservices-dispatch-action/issues/18 ). Discussing with a couple folks offline

**Comment by jakirkham** [comment]
Ok maybe have worked around the issue. Trying again

@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

(just for confirmation)

**Comment by jakirkham** [comment]
Sorry for all the churn here. This should now be good to go 🙂

**Comment by emeryberger** [comment]
It still doesn't show up as supporting Windows - is this possibly because I need to add`build: noarch: python [win]`?

**Comment by jakirkham** [comment]
The packages [are still building]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=613974&view=results ). Would give it some time to build, upload, and CDN to sync. No additional changes are needed.

**Comment by emeryberger** [comment]
Thanks a ton for your help!

**Comment by jakirkham** [comment]
Happy to help :)

**Pull request merged**
